### ISSUE TITLE
Evil support?

### ISSUE THREAD

**Issue by endrebak** [magnars/annoying-arrows-mode.el#5]
Would it be possible to add evil-support?

I am a total elisp newb, so uncertain about the best way to do it, but just using an `(if (bound-and-true-p evil-mode))` should allow you to change what arrow-advice is given depending on whether `evil-mode` is used.

```
(if (not (bound-and-true-p evil-mode)))
  (progn
    old advice...)
  (progn
    (add-annoying-arrows-advice evil-forward-char '(evil-find-char smart-forward evil-set-marker))
    (add-annoying-arrows-advice evil-backward-char '(evil-find-char-backward smart-backward evil-set-marker))
    (add-annoying-arrows-advice evil-next-line '(smart-forward ace-jump-mode evil-set-marker))
    (add-annoying-arrows-advice evil-previous-line '(smart-forward ace-jump-mode evil-set-marker))
    (add-annoying-arrows-advice evil-delete-backward-char '(evil-delete-backward-word evil-delete))))
```

Another problem is that many of the functions I want to suggest for annoying arrows advice take numerical arguments so your macro does not read them properly. Don't know if this is easy to work around or not.

I understand if this is too much work to fix and that you might not be interested. If so, is it okay if I make an evil-annoying-arrows and add it to elpa? Will change the macro to a function that has hardcoded text strings suggesting alternative motions and hope for some pull-requests.

**Comment by magnars** [comment]
I'm perfectly fine with a separate evil-annoying-arrows package, or if you want to add a pull request that's good too. :)

**Comment by endrebak** [comment]
Giving up for now, it seems some evil functions do not play well with advice.

Asked for help at [emacs.stackexchange](http://emacs.stackexchange.com/questions/7635/advising-evil-forward-char-seems-to-trigger-advice-twice)

**Comment by endrebak** [comment]
Technically it works if you do not add my suggested 'annoying-arrows-super-annoying` bool though.

There are a few things that need tweaking in additon:

```
(defun aa--commands-with-shortcuts (cmds)
  (remove-if (lambda (cmd)
               (and
                (>= (length (substitute-command-keys (format "\\[%S]" cmd))) 3)
                (string-equal
                 (substring (substitute-command-keys (format "\\[%S]" cmd)) 0 3)
                 "M-x"))) cmds))
```

Since evil has some commands that are described in merely one char, such as `/`.

**Comment by endrebak** [comment]
Just adding notes to self or anyone else that might be interested in improving this:

If you currently do `5j` x times in a row, where x is `annoying-arrows-too-far-count`, the annoying message is triggered. Should make a variable to turn this off? Low-priority thought.
